// Tokens -> CSS custom properties. Writes out/tokens.css:
//   :root                      primitives and the theme-independent semantic layer
//   :root, [data-theme=light]  semantic colours, light (the default)
//   @media (prefers-color-scheme: dark) :root:not([data-theme=light])   dark, when the OS asks for it
//   [data-theme=dark]          dark, when the page asks for it
// Usage: tsx src/tokens/build.ts [--proposal tokens/proposals/x.light.tokens.json]... [--out file.css]
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve as resolvePath } from "node:path";
import { pathToFileURL } from "node:url";
import { ROOT, THEMES, TOKENS, type Theme, type Tokens, cssVar, load, loadTheme, tokenToCss } from "./dtcg.js";

const names = (file: string) => [...load([join(TOKENS, file)]).keys()];

function block(selector: string, tokens: Tokens, list: string[], indent = "", extra: string[] = []) {
  const lines = [...extra, ...list.map((n) => `${cssVar(n)}: ${tokenToCss(tokens, tokens.get(n)!)};`)];
  return `${indent}${selector} {\n${lines.map((l) => `${indent}  ${l}`).join("\n")}\n${indent}}`;
}

export function buildCss(proposals: string[] = []): { css: string; counts: Record<string, number> } {
  const primitives = names("primitives.tokens.json");
  const semantic = names("semantic.tokens.json");
  const themed = Object.fromEntries(THEMES.map((t) => [t, names(`theme.${t}.tokens.json`)])) as Record<Theme, string[]>;
  // Theme parity: a token that exists in one mode only would fall back to nothing in the other.
  const [light, dark] = [new Set(themed.light), new Set(themed.dark)];
  const onlyOne = [...light].filter((n) => !dark.has(n)).concat([...dark].filter((n) => !light.has(n)));
  if (onlyOne.length) throw new Error(`tokens defined in one theme only: ${onlyOne.join(", ")}`);

  const tokens = Object.fromEntries(THEMES.map((t) => [t, loadTheme(t, proposals)])) as Record<Theme, Tokens>;
  const css = [
    "/* Generated by src/tokens/build.ts from tokens/*.tokens.json. Do not edit by hand. */",
    proposals.length ? `/* With proposals: ${proposals.map((p) => p.split("/").pop()).join(", ")} */` : "",
    block(":root", tokens.light, [...primitives, ...semantic]),
    block(':root,\n[data-theme="light"]', tokens.light, themed.light, "", ["color-scheme: light;"]),
    `@media (prefers-color-scheme: dark) {\n${block(':root:not([data-theme="light"])', tokens.dark, themed.dark, "  ", ["color-scheme: dark;"])}\n}`,
    block('[data-theme="dark"]', tokens.dark, themed.dark, "", ["color-scheme: dark;"]),
  ]
    .filter(Boolean)
    .join("\n\n");
  return { css: css + "\n", counts: { primitives: primitives.length, semantic: semantic.length, themed: themed.light.length } };
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const args = process.argv.slice(2);
  const proposals = args.flatMap((a, i) => (args[i - 1] === "--proposal" ? [resolvePath(a)] : []));
  const outIdx = args.indexOf("--out");
  const out = outIdx >= 0 ? resolvePath(args[outIdx + 1]) : join(ROOT, "out", "tokens.css");
  const { css, counts } = buildCss(proposals);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, css);
  const vars = css.match(/^\s*--[\w-]+:/gm)!.length;
  console.log(`   tokens -> ${out.replace(ROOT + "/", "")}: ${counts.primitives} primitives, ${counts.semantic} semantic, ${counts.themed} themed colours x ${THEMES.length} themes = ${vars} declarations`);
}
